### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#11]
Basic functionality 
- [x] handle all iso-profiles package flags 

- [ ] Openrc support 
- [ ] btrfs subvolumes creation 
- [ ] translate manjaro specific parts 

Extra features 
- [ ] set console font size based on the screen size 
- [ ] add option to chroot into installed system 
- [ ] update and readd aif ro package
- [ ] add option to install arbitrary packages with fzf
