### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#82]
0.8
- [x] restructure to non-recursive menus 
- [x] advanced and simple menu
- [x] ensure permissions for $HOME are set correctly 
- [x] filter LUKS menu to only show relevant devices 

0.9
- [ ] support for different bootloaders 
- [ ] support for hibernation 
- [x] merge edition and base installation? 
- [ ] possibly a dynamic menu?

1.0
- [x] support for btrfs subvolumes 
- [ ] complete translations
- [ ] documentation 
- [ ] scriptability - set options with command line arguments 
- [ ] configuration file?

**Comment by Chrysostomus** [comment]
This approximately what I have in mind featurewise, bug fixes not mentioned. I think 0.8 would be ready to go to stable repo and deployed with isos. 

What do you think?

**Comment by Chrysostomus** [comment]
It seems merging keyboard layout menus is not feasible, because their contents are so different.

**Comment by oberon-manjaro** [comment]
I am still confused about vconsole settings. Is it like the settings for the live session will necessarily be the same as in target? Not that it seems a real problem, I would just like to know if I got it right... Or the other question is: would there be a more or less easy way to quickly set the console keyymap at the point where language is chosen independently from vconsole settings moving to some place more logical, like what you suggested above?

**Comment by oberon-manjaro** [comment]
How about the menu thing. Are you working on this? Or should I configure it in some way or the other tonight?

**Comment by Chrysostomus** [comment]
Which menu thing? The reorganization?

vconsole.conf is set only for the target installation

**Comment by Chrysostomus** [comment]
I think I'm going to work on luks menu filteration next. Then it is either merging install_base and install_manjaro_de_wm, or redoing the menu layout. What do you think would be the best?

**Comment by oberon-manjaro** [comment]
How big of a task do you think will merging install_base and install_manjaro_de_wm be? I think it would be good to do another realease tag, soon - be it 0.8 or 0.7.5
So much has happened since the last tag and it would be good to travel to testing branch now I think.
I'm happy to help with getting the menu ready, then. How shall we configure it for now?

**Comment by Chrysostomus** [comment]
I had some weird issues trying openrc version of bspwm edition. Vconsole did not get set, and xorg was nonresponsive. 

I'd like to test the vconsole thing a bit further, then I suggest we bump the version to 0.8 and send it to testing repos.

**Comment by Chrysostomus** [comment]
Merging the two menus is maybe 1 or 2 nights, depending on how much trouble I run into.

**Comment by Chrysostomus** [comment]
Okay, vconsole.conf got set properly, the openrc system just ignores it. Not as big of a problem then.

**Comment by Chrysostomus** [comment]
I'll test the luks filteration a bit

**Comment by oberon-manjaro** [comment]
Just let me know if there's anything I should work on meanwhile. Customization works fine now :)

**Comment by Chrysostomus** [comment]
LUKS filtering now works. Open_luks menu should now only offer viable choices.

I think now we can push 0.8 to testing.

**Comment by Chrysostomus** [comment]
Can you work on the menu layout? 

You could move networking and multimedia submenu under the unconfigured desktop menu. 

I'll start looking at how to merge base and desktop functions.

**Comment by oberon-manjaro** [comment]
I'll see that I can get the menu ready by tonight and then we can create the tag, good? :+1:

**Comment by oberon-manjaro** [comment]
meanwhile I also made some extremely important config... :roll_eyes: :stuck_out_tongue_winking_eye: 

![](http://imgur.com/Oy5jyw7.png)

'password' still has the wrong color. Apart from that looks quite nice already I think :grin:

**Comment by Chrysostomus** [comment]
Very nice indeed! Downloading manjaro-architect iso now. I accidentally deleted all my manjaro bootloaders, and need a rescue disc...

**Comment by Chrysostomus** [comment]
... Got back to work. Need to sleep soon though...

**Comment by oberon-manjaro** [comment]
ok ! :) I'm at the menu right now ... :) sleep well!

**Comment by Chrysostomus** [comment]
https://github.com/Chrysostomus/manjaro-architect/tree/basestrap_merge 

Try this if you are interested. The changes are in base-util.sh

**Comment by oberon-manjaro** [comment]
Will have a look later :) :+1: 
For now I have organized the menu [like this](https://raw.githubusercontent.com/Chrysostomus/manjaro-architect/master/data/menu_layout)
Will do a test-run later if the navigation works, but I'd be rather surprised if it wouldn't. This is a great advantage now that the single menu entries are pretty much independent - cool! :)

**Comment by oberon-manjaro** [comment]
Your basestrap_merge branch looks great! I'll adjust the menu there and make that the -exp package now so we can play with that a bit more. The "common packages" section I kept thinking the whole time is not really needed since most of the listed packages listed come pre-installed with most profiles anyway and people will not know and reinstall them unnecessarily. Also, if they want more packages they can and will install them later on their system anyway. Also additionally we have the custom packages option in the advanced menu.
To me this looks just like one option too much ... :wink: If we want to keep it, maybe it should filter out the already installed packages?
Personally I would just drop that.

**Comment by oberon-manjaro** [comment]
![](http://imgur.com/Ao5m4Dj.png)
:drooling_face: :+1: 
...better than counting sheep! :zzz:

**Comment by oberon-manjaro** [comment]
Now that I wanted to adjust the menu I just realized that some principal questions are still unanswered here... :wink: If we completely merge base install with manjaro-DE-pkg install, whats the plan for the -git option, for vanilla desktops and bare net(base)install?
If again we don't want to maintain twice the same code we'll still need some kind of break point where we either continue with profile pkgs or stop and just install the base, or go somewhere else - maybe I missed what you had in mind there exactly?

**Comment by Chrysostomus** [comment]
I would suggest that we choose the iso-profiles provider with command line switch, defaulting to package. 

I think the modified install_base needs to be split into several functions. Currently it is not very readable. 

We could drop the extra packages installation, but then we need to modify the shell choice in user creation to accommodate.

**Comment by Chrysostomus** [comment]
Okay, it is much cleaner now and works okay. Except for the netinstall, that profile is entirely unsuitable for this purpose and needs to be overridden

**Comment by Chrysostomus** [comment]
Netinstall profile has following difficulties:
- checks prevent even attempting to install it with openrc because of the lack of tags. This might be remedied by simply pointing the $target_desktop to Packages-Root
- The services list has been compiled with Packages-Live and calamares in mind. This needs to be bypassed.
- No overlay. Need to skip overlay copying if netinstall

Otherwise, I'm pretty satisfied with this now. It defaults to using stable profiles, but uses git if the right tmp file is touched.

Done for tonight

**Comment by oberon-manjaro** [comment]
Do we need a netinstall profile if we can just do what base_install does now already?

**Comment by oberon-manjaro** [comment]
or is base_install now not a separate step at all any more?

**Comment by Chrysostomus** [comment]
This function does the base and profile installation in one step. This is the base installation

**Comment by oberon-manjaro** [comment]
i still don't understand what you plan with this is. what about unconfigured DEs? how will this work? do you want to drop that?

**Comment by Chrysostomus** [comment]
No, the intention is that choosing netinstall works like install_base used to. We may need to make a separate "base" item in the menu though. Netinstall does not seem to to have anything of value to source, and the name is more confusing than just "base" 

Also, the updated function uses filtered Packages-Root instead of separate package files, like you suggested.

**Comment by Chrysostomus** [comment]
But maybe dropping unconfigured desktops would not be such a bad idea. We could replace them with the following items:

- install Xorg 
- add arbitrary packages with fzf, pacli style 
- manjaro-chroot into the installation

**Comment by oberon-manjaro** [comment]
Sounds great! I will have a closer look at what you changed, soon. But normally it should be doable to just not add any overlay or Packages-Desktop and proceed with pratically Packages-Root only, right?

**Comment by Chrysostomus** [comment]
Yeah. Just Packages-Root, and some services enabled (maybeł

**Comment by oberon-manjaro** [comment]
Are we ready for the 0.8 release? Maybe just fix the fish shell thing and then I think we're looking very good, don't we? :smiley:

**Comment by Chrysostomus** [comment]
I would say so, yes

**Comment by Chrysostomus** [comment]
![2017-03-06-231306_1920x1080_scrot](https://cloud.githubusercontent.com/assets/12002226/23615861/c362487a-02c2-11e7-9c39-555b93bf508e.png)


There is still a issue with theming left....

**Comment by Chrysostomus** [comment]
It looks fine in the console, but in xorg terminals...

**Comment by Chrysostomus** [comment]
Maybe we should not set dialogrc in the script, but instead just keep it in the iso overlay? Terminal colors are unpredictable, we don't know what the user will have.

**Comment by Chrysostomus** [comment]
Alternatively we can just set the terminal colors to maia colors in the script. I think that would be nice. Can you @oberon2007 deal with the color issue before upgrading to 0.8? The fish issue should now be fixed.

**Comment by oberon-manjaro** [comment]
you are right! For some reason it didn't get copied to roots home as the other dotfiles. Maybe manjaro-live is selective there - need to check. In any case we can just do it like with the font for a live session only. That should not be a problem then.

**Comment by oberon-manjaro** [comment]
How do you mean setting terminal colors? I only know the way via .Xresources and it won't work without a relog I think. Also how should we set the colors back to what the user had and wants when the installer quits?

**Comment by oberon-manjaro** [comment]
Like this for now, maybe? Just very restrictive?

**Comment by Chrysostomus** [comment]
source this script to set the terminal colors to maia:

```
#!/bin/sh
# Base16 Bespin - Shell color setup script
# Jan T. Sott

if [ "${TERM%%-*}" = 'linux' ]; then
    # This script doesn't support linux console (use 'vconsole' template instead)
    return 2>/dev/null || exit 0
fi

color00="23/24/23" # Base 00 - Black
color01="BA/29/22" # Base 08 - Red
color02="13/87/70" # Base 0B - Green
color03="7E/80/7E" # Base 0A - Yellow
color04="33/36/34" # Base 0D - Blue
color05="3E/42/40" # Base 0E - Magenta
color06="00/CC/CC" # Base 0C - Cyan
color07="E0/E0/E0" # Base 05 - White
color08="28/29/28" # Base 03 - Bright Black
color09="CC/37/2C" # Base 08 - Bright Red
color10="16/A0/85" # Base 0B - Bright Green
color11="85/87/85" # Base 0A - Bright Yellow
color12="37/3b/38" # Base 0D - Bright Blue
color13="43/47/45" # Base 0E - Bright Magenta
color14="E0/E0/E0" # Base 0C - Bright Cyan
color15="E8/E8/E8" # Base 07 - Bright White
color16="cf/7d/34" # Base 09
color17="93/71/21" # Base 0F
color18="36/31/2e" # Base 01
color19="5e/5d/5c" # Base 02
color20="79/79/77" # Base 04
color21="9d/9b/97" # Base 06
color_foreground="8a/89/86" # Base 05
color_background="28/21/1c" # Base 00
color_cursor="8a/89/86" # Base 05

if [ -n "$TMUX" ]; then
  # tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  printf_template="\033Ptmux;\033\033]4;%d;rgb:%s\007\033\\"
  printf_template_var="\033Ptmux;\033\033]%d;rgb:%s\007\033\\"
  printf_template_custom="\033Ptmux;\033\033]%s%s\007\033\\"
elif [ "${TERM%%-*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  printf_template="\033P\033]4;%d;rgb:%s\007\033\\"
  printf_template_var="\033P\033]%d;rgb:%s\007\033\\"
  printf_template_custom="\033P\033]%s%s\007\033\\"
else
  printf_template="\033]4;%d;rgb:%s\033\\"
  printf_template_var="\033]%d;rgb:%s\033\\"
  printf_template_custom="\033]%s%s\033\\"
fi

# 16 color space
printf $printf_template 0  $color00
printf $printf_template 1  $color01
printf $printf_template 2  $color02
printf $printf_template 3  $color03
printf $printf_template 4  $color04
printf $printf_template 5  $color05
printf $printf_template 6  $color06
printf $printf_template 7  $color07
printf $printf_template 8  $color08
printf $printf_template 9  $color09
printf $printf_template 10 $color10
printf $printf_template 11 $color11
printf $printf_template 12 $color12
printf $printf_template 13 $color13
printf $printf_template 14 $color14
printf $printf_template 15 $color15

# 256 color space
printf $printf_template 16 $color16
printf $printf_template 17 $color17
printf $printf_template 18 $color18
printf $printf_template 19 $color19
printf $printf_template 20 $color20
printf $printf_template 21 $color21

# foreground / background / cursor color
if [ -n "$ITERM_SESSION_ID" ]; then
  # iTerm2 proprietary escape codes
  printf $printf_template_custom Pg 8a8986 # forground
  printf $printf_template_custom Ph 28211c # background
  printf $printf_template_custom Pi 8a8986 # bold color
  printf $printf_template_custom Pj 5e5d5c # selection color
  printf $printf_template_custom Pk 8a8986 # selected text color
  printf $printf_template_custom Pl 8a8986 # cursor
  printf $printf_template_custom Pm 28211c # cursor text
else
  printf $printf_template_var 10 $color_foreground
  printf $printf_template_var 11 $color_background
  printf $printf_template_var 12 $color_cursor
fi

# clean up
unset printf_template
unset printf_template_var
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color16
unset color17
unset color18
unset color19
unset color20
unset color21
unset color_foreground
unset color_background
unset color_cursor

```

No idea how to set the colors back

**Comment by Chrysostomus** [comment]
This is how manjaro-zsh-config sets terminal colors. Check .zshrc for all variants.

Although I have to say maia-colors is not very optimized for usage outside the installer. Open ranger with those colors to see what I mean

**Comment by oberon-manjaro** [comment]
yes, i know ;) it's just twisting the color scheme quite a lot to serve dialog's oddities ... ;)

**Comment by oberon-manjaro** [comment]
for example in dialog you can only set "green" but then it depends on where the color is applied if it will be color2 or 10 :stuck_out_tongue: 
Leaving the user behind with messed up terminal colors / or the default if he had them configured is not really an option. In that case I think we should just use the default.
We need to solve that in the future for terminal also, I know.

**Comment by oberon-manjaro** [comment]
In fact I am using maia-console's colors in the terminal, too. The only problem I see is that folders for example are too dark and hardly visible - it's maybe also what you mean in ranger?
I will play with this more in the near future...

**Comment by oberon-manjaro** [comment]
Sorry, I had to disappear for a while...
Maybe my strategy to change both dialogrc and the console theme was not a good idea. I guess l should try to achieve the same by adjusting the theme only ... I'll try that again a little later today.

**Comment by oberon-manjaro** [comment]
How are chances we finalize **v0.8** these days? Let me know if I can be of any help with reorganizing the menu. After sueridgepipe's latest comments I'd just need to know what your decision for now is, @Chrysostomus  ... :)

**Comment by Chrysostomus** [comment]
I don't know yet. I think we need to at least test openrc parts before going to stable after the bugs I recently found. 

I'm actually grown fond of the current simple style, but I think we should test @sueridgepipe suggestion with a experimental branch so we can properly compare the options

**Comment by oberon-manjaro** [comment]
Sounds very good. There were so many big changes that it will certainly be good to just stabilize and freeze the  code as the plan in fact was quite a while ago :wink:
Have you seen my PR re. **displaymanager-openrc**? Not sure if this is a proper fix, but in any case there's an issue with this.
I'd package the current state then and do some openrc installs today and maybe later these days attempt a @sueridgepiper style version on a dedicated branch.
While this looks like an opportunity to test also @papajoker 's dynmenu concept I must say that
a) I'm afraid I haven't fully grasped how it works, yet - would need to look into it some more first
b) I'd actually love to find a menu structure we agree on and stick to it rather than making it totally fluent and constantly changing it ... :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment]
I saw it, but on cellphone did not realize it was a pull request 😜. We definitely need to fix the issue. I'll take a look at it. 

I agree that we need to agree on the structure. Papajokers idea would still be useful, because it would aid making changes and allow greater flexibility in using cli switches later. But I don't have time to implement it. I'm secretly hoping that some day papajoker sends a mergeable pull request for it 😅

**Comment by Chrysostomus** [comment]
Maybe we should use a different executable name for the testing branch, so they can be installed side by side for better comparison?

**Comment by oberon-manjaro** [comment]
You mean for a different menu? Let's think about that more when we actually have on. An argument like the debug option we already have, would also be an option quite simple to build in.

**Comment by Chrysostomus** [comment]
Хорошо. So let's just smash the bugs and push 0.8 to stable first

**Comment by oberon-manjaro** [comment]
:+1:  New -dev package is in unstable. I'll do an unconfigured openrc test install shortly.

**Comment by oberon-manjaro** [comment]
Time for some trivia? :wink: 

- There have been **370** commits since **0.7.4** only.
- **manjaro-architect** has diverged from it's parent by **507** commits meanwhile.
- Original **aif** has **2836** lines of code, present **m-a** has **3279**
Looks like someone wrote an additional **443 lines**?? :laughing: 

Pretty impressive, isn't it!?

**Comment by Chrysostomus** [comment]
Kinda yes. Also the the concept has transitioned from following arch beginners guide towards more manjaro style installation. 

In terms of features, we have at least 
- started to use iso-profiles instead of static package lists 
- moved to using mhwd for driver installation 
- provided kernels from dynamic list 
- added support for openrc 
- fixed support for nilfs2 
- modified the menu structure to be non-recursive 

I think those might be the biggest additions. We have also lost 
- support for bootloaders other than grub 

This is mostly because we cannot have a static list of kernels, so automating config generation is more complicated.

**Comment by oberon-manjaro** [comment]
Once we have the alternative menu setup we can just offer both for public testing and then make a decision which one should be the default in the end. The other one can then be made available by passing an arg or so. Like that everyone should be happy :wink:

**Comment by oberon-manjaro** [comment]
As far as I can tell, EVERYTHING seems to be working as it should :smile: 

![](http://imgur.com/aTf5DDQ.png)

I made another i3 openrc and an xfce systemd install with latest version and all is looking really good proper logging included :+1: 
**0.7.4.r390.gc3694e3** is packaged both as -dev and as regular package.
If you agree, maybe you'd like to do the **0.8** realease now and make a little announcement to the valued testers? :smiley: 
I need to sleep now! :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment]
I can make an announcement once you push it to repos.

**Comment by oberon-manjaro** [comment]
You mean with the new tag? Sure.
Wanna do it now?

**Comment by oberon-manjaro** [comment]
In any case, open a new thread, will you? The old ones are soooooo long already, it's ridiculous! :wink:

**Comment by Chrysostomus** [comment]
Yeah

**Comment by oberon-manjaro** [comment]
Went through all the commits since last release again and put together a pretty impressive list in the [release announcement](https://github.com/Chrysostomus/manjaro-architect/releases/tag/0.8.0) There was one more really important thing that I could not remember the moment I wanted to write it down :stuck_out_tongue_winking_eye: - I'm tired ... 
Packages building right now, will push them in a minute.
Congratulations Matti! Awesome job! and what a pleasure to work with you and to (almost) know you (a little bit) :wink: :smile:

**Comment by oberon-manjaro** [comment]
**manjaro-architect-0.8.0-1** in unstable branch now.

**Comment by oberon-manjaro** [comment]
@Chrysostomus I added some screenshots with the github release. If you'd like to use them on the forum, they're here: :)
http://imgur.com/8uGDU5f.png
http://imgur.com/VLUmdCB.png
http://imgur.com/umr9lCt.png
http://imgur.com/OCrk30h.png
Good night now, really!! :wink:

**Comment by oberon-manjaro** [comment]
Ready for a **0.8.12** release @Chrysostomus ?

**Comment by Chrysostomus** [comment]
Absolutely

**Comment by Mauladen** [comment]
How soon will the package be updated to version 8.12?

**Comment by Chrysostomus** [comment]
Depends on who packages it. Currently I'm swamped with work, so if I do it it might take a while. If @oberon does it, maybe sooner?

**Comment by oberon-manjaro** [comment]
**0.8.12** is on unstable branch already since it was released. It's just a question of branches snapshots.
I might fast forward it today or you can install it directly if you want to have it sooner:
```
sudo pacman -U http://manjarolinux.polymorf.fr/unstable/community/x86_64/manjaro-architect-0.8.12-1-any.pkg.tar.xz
```
